### ISSUE TITLE
Add smooth scrolling

### ISSUE THREAD

**Issue by rrudol** [akai-org/frontend-workshops#21]
jQuery?

**Comment by tomaszgil** [comment]
Jeśli nikt tego nie pisze, mogę na szybko ogarnąć. :)

**Comment by rrudol** [comment]
super 👍

**Comment by tomaszgil** [comment]
A dodajemy jQuery do npm czy tylko link w htmlu?

**Comment by rrudol** [comment]
może cdn, żeby pokazać ze skrypty mogą iść również z zewnętrznych serwerów?

**Comment by tomaszgil** [comment]
Dobra, wziąłem z googlowskiego. :)

**Comment by tomaszgil** [comment]
Poszedł pull request, merguj jeśli się wszystko zgadza proszę :)

**Comment by rrudol** [comment]
Wszystko się zgadza i działa świetnie 🆒
