### ISSUE TITLE
Setup Github Pages

### ISSUE THREAD

**Issue by rrudol** [akai-org/frontend-workshops#22]
Moglibyśmy uruchomić funkcjonalność Github Pages dla tego repozytorium i dać możliwość wyświetlenia przykładowej strony z poziomu Githuba.

**Comment by hejmsdz** [comment]
Dobry pomysł, bo na razie trzeba sklonować kod, żeby zobaczyć, jak to w ogóle wygląda. Kto ma do tego dostęp? U mnie nie widać zakładki Settings repozytorium.

**Comment by rrudol** [comment]
Dałem wam uprawnienia administratora - powinno już wszystko być dostępne ;)

**Comment by hejmsdz** [comment]
Strona stoi pod adresem https://akai-org.github.io/frontend-workshops/public_html/
Da się jakoś pominąć to `public_html`?

**Comment by mateusz-stempniewicz** [comment]
Tutaj chyba jesteśmy zmuszeni podać lokalizację pliku index.html. Ewentualnie coś mi się kojarzy, że w ustawieniach można chyba podać własną domenę

**Comment by rrudol** [comment]
Niestety nie widzę takiej opcji. Generalnie i tak jest super 👍
Można zrobić plik index.html w folderze głównym, który przekierowywałby na odpowiednią ścieżkę ale chyba mija się to z celem.
